# Generated by Django 3.0.6 on 2020-05-06 17:27

import JobPosition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_column='job_title', max_length=200, verbose_name='头衔')),
                ('level', models.SmallIntegerField(db_column='level', validators=[JobPosition.models.valid_level], verbose_name='级别')),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False, verbose_name='删除标识')),
            ],
            options={
                'verbose_name': '职级',
                'verbose_name_plural': '职级',
                'db_table': 'job_position',
            },
        ),
    ]
