# Generated by Django 3.0.6 on 2020-05-06 17:27

import Score.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id', max_length=10, verbose_name='user_id')),
                ('point', models.SmallIntegerField(validators=[Score.models.valid_point])),
                ('project_id', models.IntegerField(db_column='project_id', verbose_name='项目id')),
                ('create_time', models.DateField(auto_now=True)),
                ('creater', models.IntegerField(db_column='creater', verbose_name='评分人id')),
            ],
            options={
                'verbose_name': '得分',
                'verbose_name_plural': '得分',
                'db_table': 'score',
            },
        ),
    ]
