# Generated by Django 3.0.6 on 2020-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(db_column='message', max_length=1000, verbose_name='汇报信息')),
                ('image_url', models.CharField(blank=True, db_column='image_url', max_length=100, verbose_name='图片地址')),
                ('video_url', models.CharField(blank=True, db_column='video_url', max_length=100, verbose_name='视频地址')),
                ('project_id', models.IntegerField(db_column='project_id', verbose_name='项目id')),
                ('creater', models.IntegerField(db_column='creater', verbose_name='汇报人id')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '汇报',
                'verbose_name_plural': '汇报',
                'db_table': 'report',
            },
        ),
    ]
