# Generated by Django 3.0.6 on 2020-05-06 17:27

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(db_column='uid', primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='姓名')),
                ('sex', models.BooleanField(db_column='sex', default=True, verbose_name='性别')),
                ('age', models.SmallIntegerField(db_column='age', validators=[User.models.valid_age], verbose_name='年龄')),
                ('telephone', models.IntegerField(db_column='telephone', verbose_name='电话')),
                ('job_level', models.SmallIntegerField(db_column='level', verbose_name='职级id')),
                ('department_ids', models.CharField(db_column='department_ids', max_length=200, verbose_name='部门id')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
